In [22]:
import numpy as np
import pandas as pd
import json

# Loading evidence from json

In [23]:
with open("../data/raw/release_evidences.json") as file:
	data = json.load(file)

In [24]:
B_type_data = {}
for i in data:
    if data[i]['data_type'] == "B":
        B_type_data[i] = data[i]

In [25]:
B_type_data_colnames = []
for i in B_type_data:
    B_type_data_colnames.append(i)

# Train

In [28]:
df = pd.read_csv("../data/raw/release_train_patients.csv")
df.head()

all_clear_rows = []
for i in df['EVIDENCES']:
	row = i.split("', '")
	row[-1] = row[-1][:-2]
	row[0] = row[0][2:]
	clear_row = []
	for i in row:
		if "@" not in i:
			clear_row.append(i)
	all_clear_rows.append(clear_row)

df['EVIDENCE_clear'] = all_clear_rows

zeros = pd.DataFrame(np.zeros((len(all_clear_rows), 208)).astype(int), columns=B_type_data_colnames)
for i in range(len(all_clear_rows)):
    zeros.loc[i, all_clear_rows[i]] = 1
    
zeros['SEX'] = (df['SEX'] == "M").astype(int)
zeros['PATHOLOGY'] = df['PATHOLOGY'] 
zeros.to_csv("../data/processed/train.csv")

zeros.head()

,E_91,E_53,E_159,E_129,E_154,E_155,E_210,E_140,E_51,E_75,...,E_121,E_120,E_142,E_195,E_183,E_224,E_223,E_5,SEX,PATHOLOGY
0,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,URTI
1,1,1,0,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,HIV (initial infection)
2,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Pneumonia
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,URTI
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,URTI

# Test

In [30]:
df = pd.read_csv("../data/raw/release_test_patients.csv")
df.head()

all_clear_rows = []
for i in df['EVIDENCES']:
	row = i.split("', '")
	row[-1] = row[-1][:-2]
	row[0] = row[0][2:]
	clear_row = []
	for i in row:
		if "@" not in i:
			clear_row.append(i)
	all_clear_rows.append(clear_row)

df['EVIDENCE_clear'] = all_clear_rows

zeros = pd.DataFrame(np.zeros((len(all_clear_rows), 208)).astype(int), columns=B_type_data_colnames)
for i in range(len(all_clear_rows)):
    zeros.loc[i, all_clear_rows[i]] = 1
    
zeros['SEX'] = (df['SEX'] == "M").astype(int)
zeros['PATHOLOGY'] = df['PATHOLOGY'] 
zeros.to_csv("../data/processed/test.csv")

zeros.head()

,E_91,E_53,E_159,E_129,E_154,E_155,E_210,E_140,E_51,E_75,...,E_121,E_120,E_142,E_195,E_183,E_224,E_223,E_5,SEX,PATHOLOGY
0,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,GERD
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Bronchitis
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Acute dystonic reactions
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Acute laryngitis
4,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,URTI

# Valid

In [31]:
df = pd.read_csv("../data/raw/release_validate_patients.csv")
df.head()

all_clear_rows = []
for i in df['EVIDENCES']:
	row = i.split("', '")
	row[-1] = row[-1][:-2]
	row[0] = row[0][2:]
	clear_row = []
	for i in row:
		if "@" not in i:
			clear_row.append(i)
	all_clear_rows.append(clear_row)

df['EVIDENCE_clear'] = all_clear_rows

zeros = pd.DataFrame(np.zeros((len(all_clear_rows), 208)).astype(int), columns=B_type_data_colnames)
for i in range(len(all_clear_rows)):
    zeros.loc[i, all_clear_rows[i]] = 1
    
zeros['SEX'] = (df['SEX'] == "M").astype(int)
zeros['PATHOLOGY'] = df['PATHOLOGY'] 
zeros.to_csv("../data/processed/valid.csv")

zeros.head()

,E_91,E_53,E_159,E_129,E_154,E_155,E_210,E_140,E_51,E_75,...,E_121,E_120,E_142,E_195,E_183,E_224,E_223,E_5,SEX,PATHOLOGY
0,0,1,0,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,Anemia
1,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,Panic attack
2,1,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Influenza
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,Anemia
4,0,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,Boerhaave